### ISSUE TITLE
The "K2 Items" button is not displayed if K2 extension has been installed after the fill it up extension's installation

### ISSUE THREAD

**Issue by Yiannistaos** [joomlaworks/fill-it-up-for-joomla#1]
On a clean Joomla! 3.6.x installation I've installed the "fill it up" extension. The K2 is not installed yet. 

After visiting the Fill it up extension's page, the two buttons in Extensions sidebar (Joomla! Articles, and Joomla! Users) are displaying properly in the component (backend).

Then I've installed the K2 component.

After visiting the Fill it up extension's page again, still, only the two buttons in Extensions sidebar (Joomla! Articles, and Joomla! Users) have been displayed in the component (backend), without the third button "K2 Items".

I've installed again (upgrade) the "Fill it up" extension and then the button "K2 Item" has been displayed correctly now.

Maybe there is a small bug if the K2 is installed after the fill it up extension, maybe not :)

**Comment by fevangelou** [comment]
Fill It Up has 3 plugins in its own group (/plugins/fillitup). Make sure that they are all enabled in Joomla.

**Comment by fevangelou** [comment]
Each button is triggered by the presence of its related plugin. We did this to allow some sort of extending for other components as well. All 3 plugins that ship with the component are enabled by default upon installation. As a remedy, simply re-install.
