### ISSUE TITLE
Does not working with PHP 7.x

### ISSUE THREAD

**Issue by Yiannistaos** [joomlaworks/fill-it-up-for-joomla#2]
On PHP7, the progress remains to 0%.

The error logs said: 

PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; upload has a deprecated constructor in \administrator\components\com_jw_fillitup\lib\class.upload.php on line 624

**Comment by fevangelou** [comment]
We use a 3rd party class here (https://github.com/verot/class.upload.php) which I think was recently updated to work with PHP 7. I've noted it down to update the class on the next update.

**Comment by fevangelou** [comment]
Released v1.1.0 to resolve this issue: https://github.com/joomlaworks/fill-it-up-for-joomla/releases/tag/1.1.0

Download from: https://www.joomlaworks.net/downloads/?f=jw_fillitup_for_joomla-v1.1.0_j3.x.zip
